##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
#
# @section DESCRIPTION
# Collects sources for a build.
##
Import('env')

# gather sources
l_sources = [ 'solvers/Roe.cpp',
              'patches/WavePropagation1d.cpp',
              'setups/dambreak/DamBreak1d.cpp',
              'io/Csv.cpp',
              'solvers/fwave.cpp',
              'setups/shockshock/ShockShock.cpp',
              'setups/rarerare/RareRare.cpp',
              'setups/subcriticalflow/SubcriticalFlow.cpp',
              'setups/supercriticalflow/SupercriticalFlow.cpp',
              'setups/tsunamievent1d/TsunamiEvent1d.cpp']

for l_so in l_sources:
  env.sources.append( env.Object( l_so ) )

env.standalone = env.Object( "main.cpp" )

# gather unit tests
l_tests = [ 'tests.cpp',
            'solvers/Roe.test.cpp',
            'patches/WavePropagation1d.test.cpp',
            'io/Csv.test.cpp',
            'setups/dambreak/DamBreak1d.test.cpp',
            'solvers/fwave.test.cpp',
            'setups/shockshock/ShockShock.test.cpp',
            'setups/rarerare/RareRare.test.cpp',
            'setups/subcriticalflow/SubcriticalFlow.test.cpp',
            'setups/supercriticalflow/SupercriticalFlow.test.cpp']

for l_te in l_tests:
  env.tests.append( env.Object( l_te ) )

Export('env')