##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install scons 
          sudo apt-get install valgrind 
          sudo apt-get install cppcheck
          sudo apt-get install zlib1g-dev libhdf5-dev libnetcdf-dev
          git submodule init 
          git submodule update 

      - name: Static Code Analysis
        run:
          cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Sanitize
        run: |
          scons mode=debug+san
          chmod +x /build/tests
          ./build/tests
          chmod +x build/tests
          ./build/tsunami_lab
          scons mode=release+san
          chmod +x build/tsunami_lab
          ./build/tsunami_lab

      - name: Valgrind
        run: |
          scons mode=debug
          chmod +x build/tests
          chmod +x build/tsunami_lab
          valgrind ./build/tests
          valgrind ./build/tsunami_lab 

      - name: Release
        run: |
          scons
          chmod +x build/tests
          chmod +x build/tsunami_lab
          ./build/tests
          ./build/tsunami_lab
