# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tester"
  tester:
    # The type of runner that the job will run on
    runs-on: Self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v4
      - name: Dependices
        run: |
          sudo apt-get update 
          sudo apt-get install scons 
          sudo apt-get install valgrind 
          sudo apt-get install cppcheck 
          git submodule init 
          git submodule update 

      - name: Static Code Analysis
        run:
          cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Sanitize
        run: |
          scons mode=debug+san
          ./build/tests
          ./build/tsunami_lab 
          scons mode=release+san
          ./build/tests
          ./build/tsunami_lab 

      - name: Valgrind
        run: |
          scons mode=debug
          valgrind ./build/tests
          valgrind ./build/tsunami_lab

      - name: Release
        run: |
          scons
          ./build/tests
          ./build/tsunami_lab

